package jp.skd.lilca.mhf.lib.skill_gain;

/**
 * ŠeíƒŠƒeƒ‰ƒ‹‚ğéŒ¾‚µ‚½ƒNƒ‰ƒX
 */
public class SkillDefines {
	/**
	 * ŠeƒXƒLƒ‹‚ÌƒCƒ“ƒ^[ƒtƒF[ƒX—p‚ÌIDƒŠƒXƒg
	 */
	public static final String[] keyList = {
		// ‘Ì—ÍEƒXƒ^ƒ~ƒiŒn
		"list_skill_preference0101",
		"list_skill_preference0102",
		"list_skill_preference0103",
		"list_skill_preference0104",
		"list_skill_preference0105",
		"list_skill_preference0106",
		"list_skill_preference0107",
		"list_skill_preference0108",
		"list_skill_preference0109",
		// UŒ‚Œn
		"list_skill_preference0201",
		"list_skill_preference0202",
		"list_skill_preference0203",
		"list_skill_preference0204",
		"list_skill_preference0205",
		"list_skill_preference0206",
		"list_skill_preference0207",
		"list_skill_preference0208",
		"list_skill_preference0209",
		"list_skill_preference0210",
		"list_skill_preference0211",
		"list_skill_preference0212",
		"list_skill_preference0213",
		"list_skill_preference0214",
		"list_skill_preference0215",
		"list_skill_preference0216",
		"list_skill_preference0217",
		"list_skill_preference0218",
		"list_skill_preference0219",
		"list_skill_preference0220",
		"list_skill_preference0221",
		"list_skill_preference0222",	// add 2013/6/26
		"list_skill_preference0223",	// add 2013/6/26
		// –hŒäŒn
		"list_skill_preference0301",
		"list_skill_preference0302",
		"list_skill_preference0303",
		"list_skill_preference0304",
		"list_skill_preference0305",
		// Œ•mŒn
		"list_skill_preference0401",
		"list_skill_preference0402",
		"list_skill_preference0403",
		"list_skill_preference0404",
		"list_skill_preference0405",
		"list_skill_preference0406",
		"list_skill_preference0407",
		"list_skill_preference0408",
		"list_skill_preference0409",
		"list_skill_preference0410",
		"list_skill_preference0411",
		"list_skill_preference0412",
		"list_skill_preference0413",		
		// ƒKƒ“ƒi[Œn
		"list_skill_preference0501",
		"list_skill_preference0502",
		"list_skill_preference0503",
		"list_skill_preference0504",
		"list_skill_preference0505",
		"list_skill_preference0506",
		"list_skill_preference0507",
		"list_skill_preference0508",
		"list_skill_preference0509",
		"list_skill_preference0510",
		"list_skill_preference0511",
		"list_skill_preference0512",
		"list_skill_preference0513",
		"list_skill_preference0514",
		"list_skill_preference0515",
		"list_skill_preference0516",
		"list_skill_preference0517",
		"list_skill_preference0518",
		"list_skill_preference0519",	// add 2013/6/26
		// ‘Ï«Œn
		"list_skill_preference0601",
		"list_skill_preference0602",
		"list_skill_preference0603",
		"list_skill_preference0604",
		"list_skill_preference0605",
		"list_skill_preference0606",
		// ó‘ÔˆÙíŒn
		"list_skill_preference0701",
		"list_skill_preference0702",
		"list_skill_preference0703",
		"list_skill_preference0704",
		"list_skill_preference0705",
		"list_skill_preference0706",
		"list_skill_preference0707",
		"list_skill_preference0708",
		"list_skill_preference0709",
		"list_skill_preference0710",	// add 2013/6/26
		// ‚»‚Ì‘¼‚Ìƒ_ƒ[ƒW•ÛŒìŒn
		"list_skill_preference0801",
		"list_skill_preference0802",
		"list_skill_preference0803",
		"list_skill_preference0804",
		"list_skill_preference0805",
		"list_skill_preference0806",
		"list_skill_preference0807",
		"list_skill_preference0808",
		"list_skill_preference0809",
		"list_skill_preference0810",
		"list_skill_preference0811",
		"list_skill_preference0812",
		"list_skill_preference0813",
		// ƒAƒCƒeƒ€g—pE’²‡Œn
		"list_skill_preference0901",
		"list_skill_preference0902",
		"list_skill_preference0903",
		"list_skill_preference0904",
		"list_skill_preference0905",
		"list_skill_preference0906",
		"list_skill_preference0907",
		"list_skill_preference0908",
		"list_skill_preference0909",
		"list_skill_preference0910",
		"list_skill_preference0911",
		"list_skill_preference0912",
		"list_skill_preference0913",
		"list_skill_preference0914",
		"list_skill_preference0915",
		"list_skill_preference0916",
		// ƒ}ƒbƒvE’T’mŒn
		"list_skill_preference1001",
		"list_skill_preference1002",
		"list_skill_preference1003",
		// ÌWE‰^”ÀŒn
		"list_skill_preference1101",
		"list_skill_preference1102",
		"list_skill_preference1103",
		"list_skill_preference1104",
		// •ñVEƒ‚ƒ“ƒXƒ^[Œn
		"list_skill_preference1201",
		"list_skill_preference1202",
		"list_skill_preference1203",
		"list_skill_preference1204",
		"list_skill_preference1205",
		"list_skill_preference1206",
		"list_skill_preference1207",
		// ‹ZŒn
		"list_skill_preference1301",
		"list_skill_preference1302",
		"list_skill_preference1303",
		"list_skill_preference1304",
		"list_skill_preference1305",
		"list_skill_preference1306",
		"list_skill_preference1307",
		"list_skill_preference1308",
		"list_skill_preference1309",
		"list_skill_preference1310",
		"list_skill_preference1311",
	};
	/**
	 * ŠeƒXƒLƒ‹‚ÌƒCƒ“ƒ^[ƒtƒF[ƒX—p‚ÌID‚É‘Î‰‚µ‚½ƒXƒLƒ‹–¼ƒŠƒXƒg
	 */
	public static final String[] nameList = {
		// ‘Ì—ÍEƒXƒ^ƒ~ƒiŒn
		"‰ñ•œ‘¬“x",
		"‘Ì—Í",
		"‚Í‚ç‚Ö‚è",
		"‰ñ•œ",
		"ƒXƒ^ƒ~ƒi",
		"H–",
		"H‚¢‚µ‚ñ–V",
		"‚Æ‚ñ‚¸‚ç",
		"‹C—Í‰ñ•œ",
		// UŒ‚Œn
		"UŒ‚",
		"“ÁêUŒ‚",
		"”š’e‹­‰»",
		"–Cpt",
		"’ê—Í",
		"’Bl",
		"‘Ìp",
		"ãJ",
		"‰Î‘®«UŒ‚",
		"…‘®«UŒ‚",
		"—‹‘®«UŒ‚",
		"•X‘®«UŒ‚",
		"—´‘®«UŒ‚",
		"’fH",
		"—­‚ß’Zk",
		"•ŠíJ‚«",
		"‘®«UŒ‚",
		"„Œ‚",
		"ˆê‘M",
		"’ÉŒ‚",
		"‹t‹«",
		"ˆê•C˜T",		// add 2013/6/26
		"“{",		// add 2013/6/26
		// –hŒäŒn
		"–hŒä",
		"ƒK[ƒh«”\",
		"©“®–hŒä",
		"¶–½—Í",
		"”½Ë",
		// Œ•mŒn
		"a‚ê–¡",
		" ",
		"Œ¤‚¬t",
		"”šŒ‚Œ•",
		"–Ò“ÅŒ•",
		"–ƒáƒŒ•",
		"‡–°Œ•",
		"‰Î‰ŠŒ•",
		"…ŒƒŒ•",
		"—‹_Œ•",
		"•XŒ‹Œ•",
		"—´‰¤Œ•",
		"Œ•p",		
		// ƒKƒ“ƒi[Œn
		"’Êí’e‹­‰»",
		"ŠÑ’Ê’e‹­‰»",
		"U’e‹­‰»",
		"’Êí’e’Ç‰Á",
		"ŠÑ’Ê’e’Ç‰Á",
		"U’e’Ç‰Á",
		"—­’e’Ç‰Á",
		"ŠgU’e’Ç‰Á",
		"“Å•r’Ç‰Á",
		"–ƒáƒ•r’Ç‰Á",
		"‡–°•r’Ç‰Á",
		"‘•“U”",
		"˜AË",
		"‘•“U",
		"”½“®",
		"¸–§ËŒ‚",
		"’e’²‡",
		"‘¬Ë",
		"‘•’…",		// add 2013/6/26
		// ‘Ï«Œn
		"‘S‘Ï«UP",
		"‰Î‘Ï«",
		"…‘Ï«",
		"•X‘Ï«",
		"—‹‘Ï«",
		"—´‘Ï«",
		// ó‘ÔˆÙíŒn
		"“Å",
		"–ƒáƒ",
		"‡–°",
		"‹Câ",
		"’EL",
		"‘Ïá",
		"º‘Ñ",
		"‘Î–hŒäDOWN",
		"‘Ïó‘ÔˆÙí",
		"‘ÏŒ",		// add 2013/6/26
		// ‚»‚Ì‘¼‚Ìƒ_ƒ[ƒW•ÛŒìŒn
		"’®Šo•ÛŒì",
		"•—ˆ³",
		"‘Ïk",
		"‰ñ”ğ«”\",
		"‘Ï‹",
		"‘ÏŠ¦",
		"“‚İ–³Œø",
		"’nŒ`",
		"R”»",
		"‚Ğ‚ç‚ß‚«",
		"ó‚¯g",
		"ª«",
		"Œx‰ú",
		// ƒAƒCƒeƒ€g—pE’²‡Œn
		"Lˆæ",
		"Œø‰Ê‘±",
		"‹C‚Ü‚®‚ê",
		"“Š±",
		"“÷Ä‚«",
		"’Ş‚è",
		"’²‡¬Œ÷—¦",
		"˜B‹àp",
		"‹­Œ¨",
		"“J‚«–¼l",
		"‚‘¬İ’u",
		"ƒiƒCƒtg‚¢",
		"’²‡t",
		"ël",
		"ŒÛ•‘",
		"“S˜r",
		// ƒ}ƒbƒvE’T’mŒn
		"ç—¢Šá",
		"’n}",
		"‹C”z",
		// ÌWE‰^”ÀŒn
		"‚‘¬ûW",
		"”‚¬æ‚è",
		"‰^”À",
		"Ìæ",
		// •ñVEƒ‚ƒ“ƒXƒ^[Œn
		"‰^‹C",
		"ƒ‚ƒ“ƒXƒ^[",
		"ˆ³—Í",
		"•ßŠlãè",
		"‚¢‚½‚í‚è",
		"ƒuƒŠ[ƒ_[",
		"‹~‰‡",
		// ‹ZŒn
		"•ĞèŒ•‹Z",
		"‘oŒ•‹Z",
		"‘åŒ•‹Z",
		"‘¾“‹Z",
		"’È‹Z",
		"ë—Â“J‹Z",
		"‘„‹Z",
		"e‘„‹Z",
		"Œye‹Z",
		"de‹Z",
		"‹|‹Z",
	};
	/**
	 * ”é“`ƒXƒLƒ‹‚ÌƒŠƒXƒg
	 */
	public static final String[] hidenNameList = {
		"•ĞèŒ•‹Z",
		"‘oŒ•‹Z",
		"‘åŒ•‹Z",
		"‘¾“‹Z",
		"’È‹Z",
		"ë—Â“J‹Z",
		"‘„‹Z",
		"e‘„‹Z",
		"Œye‹Z",
		"de‹Z",
		"‹|‹Z",
	};
}
